### PR TITLE
Additional reuse options and rbind-tsmm rewrite.

### PR DESCRIPTION
**Pull request by phaniarnab**

### CODE REVIEW

**Comment by mboehm7** [comment]
LGTM - thanks for the patch @phaniarnab. I additionally merged the ReuseOptions and CacheType enums as they were kind of redundant.

**Comment by phaniarnab** [comment]
> LGTM - thanks for the patch @phaniarnab. I additionally merged the ReuseOptions and CacheType enums as they were kind of redundant.

Thanks. I kept those separated because CacheType is internal and can grow beyond those 3 types, whereas ReuseOptions is for users.

**Comment by mboehm7** [comment]
good point. Let's keep them as one for now though as we anyway need to expose these types; otherwise they are unusable from outside SystemDS.

**Comment by phaniarnab** [comment]
That is true. Thanks.

**Comment by mboehm7** [comment]
btw, the reason why `append` was used for binary rbind/cbind was to differentiate between binary and nary append during instructions parsing as the latter is not supported for frames. So I'll revert my change and first support lineage tracking for nary rbind/cbind. Once we made the switch to replace frames with our new data tensors, we can clean this up.

**Pull request closed without merging**
