### PR TITLE
Implement federated MV/VM-Multiplication for L2SVM

### PR DESCRIPTION
**Pull request by kev-inn**
Provides a basic implementation for MV/VM-federated operations, which allows us to execute the l2svm builtin.

### CODE REVIEW

**Comment by kev-inn** [comment]
It seems my implementation of async with `CompletableFutures` is faulty, I will have a look into that.

**Comment by kev-inn** [comment]
Btw. the federated instructions for will currently not be shown in the explain plan because the CP instructions are replaced very late when we run the script.

**Comment by kev-inn** [comment]
There is still a problem with some configurations (the configuration file in `conf` causes a request of the whole data for some reason)

**Comment by mboehm7** [comment]
LGTM - thanks @kev-inn that's a great start. Note that I refactored the code in order to move the operations as much as possible out of ProgramBlock and MatrixObject, which is too central to SystemDS for this. I also modified the caching logic to avoid redundant transfers and proper state management. In the future, we should propagate a federated flag during parsing, directly compile federated instructions if we can and only used the `checkAndReplace` if there were dynamic assignments the compiler could not reason about.

**Pull request closed without merging**
