### PR TITLE
Improved test, compile and package

### PR DESCRIPTION
**Pull request by Baunsgaard**
- Run tests in parallel Using Maven Surefire
- Removed old integration test plugin
- Set logging to Warning Tests
- Commented out System.out.println Time duration of automatedTestBase
- Commented out System.out.println compression estimation in estim
- Commented out unused dependency Yarn pom.xml
- Including not thread safe flag for testing
  - From dependency jcip-annotations
- Optimize command script .travis.yml
- Change to travis xenial dist (recommended)
- Remove Scala dependency from pom.xml (not used)
- Remove copy to resources (was depricated)
- Cleanup in pom.xml
- Update .gitignore
  - .factorypath

- Util test fix logging, and format

### CODE REVIEW

**Comment by Baunsgaard** [comment]
| Experiments        | Name           | Internal time | Full time | nr tests | Comment + yesNo on thread safe |
| -------------      | --- | --- | --- | --- | --- |
| Application | ApplyTransformTest                   | 2.649  | 5.468    | 7  |  No |
| ---         | ArimaTest                            | 17.33  | 19.231   | 1  |  No |
| ---         | A**                                  | ...    | 21.846   | 8  |  ... |
| ---         | BivariateCategoricalCategoricallTest | 3.711  | 6.392    | 3  |  No |
| ---         | BivariateOrdinalOrdinalTest          | 3.2    | 5.9      | 2  |  No |
| ---         | BivariateScaleCategoricalTest        | 2.495  | 5.096    | 2  |  No |
| ---         | BivariateScaleScaleTest              | 2.352  | 5.067    | 2  |  No |
| ---         | B**                                  | ...    | 11.041   | 9  |  ... |
| ---         | CsplineCGTest                        | 3.596  | 6.210    | 3  |  No |
| ---         | CsplineDSTest                        | 3.252  | 5.879    | 3  | Fail In all Run No |
| ---         | C**                                  | ...    | 8.910    | 6  |  ... |
| ---         | A**,B**,C**                          | ...    | 33.196   | 23 |  ... |
| ---         | GLMTest                              | 221.158| 3m43.9   | 31 | Fail In all Run No & Fails normally 1 test |
| ---         | GNMFTest                             | 1.352  | 3.933    | 1  |  No |
| ---         | HITSTest                             | 32.712 | 35.384   | 1  |  No |
| ---         | ID3Test                              | 112.568| 1m55.531 | 2  | Fail In all Run No & Requires R Packages|
| ---         | L2SVMTest                            | 25.37  | 28.123   | 9  |  No |
| ---         | LinearLogRegTest                     | 25.438 | 28.286   | 7  | Fail In all Run No |
| ---         | LinearRegressionTest                 | 20.81  | 23.715   | 7  |  No |
| ---         | MDABivariateStatsTest                | 62.898 | 1m5.782  | 4  |  No |
| ---         | MultiClassSVMTest                    | 33.601 | 36.525   | 9  |  No |
| ---         | NaiveBayesParforTest                 | 30.179 | 33.021   | 6  |  No |
| ---         | NaiveBayesTest                       | 27.837 | 30.597   | 6  |  No |
| ---         | NNTest                               | 70.316 | 1m14.356 | 1  |  Fail In all Run No + "WelcomeToSystemDS" () |
| ---         | OrderStatisticsTest                  | 0.736  | 3.546    | 1  |  Fail In all Run No |
| ---         | M**,Na**,O**                         | ...    | 2m27.735s  | 26 |  ... |
| ---         | PageRankTest                         | 3.38   | 6.361    | 3  |  No |
| ---         | ParForBivariateStatsTest             | 6.485  | 9.526    | 2  |  Fail In all Run Yes |
| ---         | ParForCorrelationTest                | 9.106  | 12.078   | 7  |  Fail In all Run Yes |
| ---         | ParForCorrelationTestLarge           | 15.682 | 18.612   | 2  |  Fail In all Run Yes |
| ---         | ParForCVMulticlassSVMTest            | 9.647  | 12.526   | 6  |  Fail In all Run Yes |
| ---         | ParForNaiveBayesTest                 | 75.646 | 1m18.537 | 8  |  Fail In all Run Yes |
| ---         | ParForSampleTest                     | 15.609 | 18.573   | 4  | Yes |
| ---         | Par**                                | ---    | 1m59.2 | 29  |  NO, Switched to Not thread Safe |
| ---         | P**                                  | ---    | 1m59.59 | 32  | --- |
| ---         | ScalableDecompositionTest            | 10.81  | 13.742   | 2  |  Fail In all Run Yes |
| ---         | UnivariateCategoricalTest            | 2.386  | 5.349    |    |  Fail In all Run No |
| ---         | UnivariateUnweightedScaleDenseTest   | ???    | 6.458    | 12 | R Fails (tried with both threadsafe and not) |
| ---         | UnivariateUnweightedScaleSparseTest  | ???    | 6.458    | 12 | R Fails |
| ---         | UnivariateWeightedScaleDenseTest     | ???    | 6.458    | 12 | R Fails |
| ---         | UnivariateWeightedScaleSparseTest    | ???    | 6.458    | 12 | R Fails |
| ---         | WelchTTest                           | 3.365  | 6.365    | 3  |  No |
| ---         | S**,W**                              | ---    | 15.122   | 5  |  ... |

**Comment by Baunsgaard** [comment]
aggregate.**    
real       6m11.898s
user    11m45.996s

50% in R script.
Practically not using parallelization

**Comment by Baunsgaard** [comment]
append.**
real    8m2.632s
user    16m53.969s

R Time:  5m26 68%

**Comment by Baunsgaard** [comment]
aggregate is now:
real    2m27.627s
user    29m13.163s

Before 8m in serial execution now 2.5 min.

Also TensorSumTest indicates there is an error in chosing spark execution or local execution

**Comment by Baunsgaard** [comment]
Total Test time: 1 Hour 10 min.
Previously 3 hours 10 min.
Test executed with Xms 4G Xmx 6G.
Total parallel max tests: 12

| Experiments        | Name           |  Full time | nr tests | R Time| Comment + yesNo on thread safe |
| -------------      | --- | --- | --- | --- | --- |
| Applications| **                                                      | 6m10.135 |  194, Failures: 49  ||  ---  |
| Functions   | aggregate                                               | 2m26  |  509 fail 8  ||  ---  |
| Functions   | append                                                  | 4m16.632s  | 43 ERROR in appendMatrixTest  | 68% |  ---  |
| Functions   | binary                                                  | 8m54.504 | 975, Failures: 29 | |  FYI (just this was previously < 1 hour)  |
| Functions   | buildin                                                 | 3m31.599  | 135, Failures: 16             | |  OOM  |
| Functions   | c*.**                                                   | 8m55.708  | 672, Failures: 15, Errors: 1 | |  OOM  |
| Functions   | data                                                    | NeverEnds  | ?? | |   |
| Functions   | DNN                                                     | 40.878  | 96 | 60% | Fully Parallel  |
| Functions   | federated                                               | 5.513  | Fails |  |  |
| Functions   | frame                                                   | 1m1.93 | 131 | 10%  |  |
| Functions   | indexing                                                | 2m14.038 | 64 | 30%  |  |
| Functions   | io                                                      |  31.027 | 110, Failures: 59, Errors: 2 | 10% |  |
| Functions   | jmlc                                                    |  10.186 | 66| 10% |  |
| Functions   | lineage                                                 |  19.411 | 52, Failures: 2 | 0% |  |
| Functions   | misc                                                    |  1m33.254 | 479, Failures: 1 | 0% |  |
| Functions   | mlcontext                                               |  2m52.172 | 298, Failures: 4, Errors: 2, | 0% |  |
| Functions   | f*,i*,l*,m*                                             |  10min |  1246, Failures: 89, Errors: 9 | |  |
| Functions   | nary                                                    |  49.393 | 56 | 50% |  |
| Functions   | parameterserv                                           |  4m30.796|  | 0% | Partially Parallel Using much resources and memory |
| Functions   | parfor                                                  |  2m31.653 | 184 | 50% |  |
| Functions   | quarternary                                             |  3m4.486 | 153| 50% |  |
| Functions   | recompile                                               |  1m51.764 | 178| 50% |  |
| Functions   | reorg                                                   |  1m35.854s | 148 | 50% |  |
| Functions   | ternary                                                 |  1m22.231 | 170 | 50% |  |
| Functions   | transform                                               |  23.517 | 104 | 0% |  |
| Functions   | unary                                                   | 6m51.201 | 462 | 50% |  |
| Functions   | updateinplace                                           | 5.514  | 15 | 0% |  |
| Functions   | vect                                                    | 20.493 | 28 | 50% |  |
| Functions   | n*,par*,q*,r*,t*,u*,v*                                  |  19m58.604s | 1534, Failures: 0, Errors: 0, | |  |

**Comment by mboehm7** [comment]
LGTM - thanks @Baunsgaard for the cleanups. I only added the GNMF testcases back to keep testing with different sizes.

**Pull request closed without merging**
